language: python
python: 3.5

install:
        - sudo apt-get update
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda update -n base conda-env
        - conda env create
        - source activate dryad

script:
        - pytest -vv dryadic/tests/test_mtypes.py
        - pytest -vv dryadic/tests/test_mcombs.py
        - python dryadic/tests/test_cohorts.py
        - python dryadic/tests/test_pipes.py
        - python dryadic/tests/test_kbtl.py
        - python dryadic/tests/test_stan.py
        - python dryadic/tests/test_txs.py

notifications:
        email:
                - grzadkow@ohsu.edu

